eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
      
spring: 
  application:
    name: mapps-szzj     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.160.103:5432/mr
    username: mr
    password: 123456 

flywaydb: 
  locations: db/migration
    
mybatis:  
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.szzj.entity

server: 
  port: 18014    
 
management:
  context-path: /__mng__
  port: 38013
  address: 127.0.0.1    
  
api:
  endpoint: /api
  key: -CfPhxfqTIOQagwZGCh4sg
  secret: xnRtQYYEub7PKrKWzMiE2DKr9XxoKRCbtHgh
  getaccountreport: https://www.zoomus.cn/v1/report/getaccountreport
  getmeetinginfo: https://www.zoomus.cn/v1/meeting/get
  endmeeting: https://www.zoomus.cn/v1/meeting/end
    
  
priv:
  roles: 
    admin: 
      - mapps.fileservice.file.upload 
      - mapps.fileservice.file.download 
      - mapps.channel.add
      - mapps.channel.edit
      - mapps.channel.query
      - mapps.channel.detail
      - mapps.channel.endMeeting
    user:  
      - mapps.fileservice.file.upload 
      - mapps.fileservice.file.download 
      - mapps.channel.add
      - mapps.channel.edit
      - mapps.channel.query
      - mapps.channel.detail
      - mapps.channel.endMeeting

mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: meetingroommng
    appType: 4
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: https://miap.cc:8209/PageRedirect?path=login.jsp
  

services: 
  fileservice:
    serviceUrl: http://192.168.160.162:9081/api
    appKey: meetingroom
    appSecret: FHuma025
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload
    webRoot: http://192.168.160.162/
    root: D:/IMG/
    
meetingroom:
  privilage:
    whiteList: true
    
client: 
  appId: szzj
  appName: 深圳质检

logging:
  path: logs
  
