eureka:
  client:
    enabled: false
      
spring: 
  application:
    name: mapps-feedback     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@192.168.160.45:1521:orcl
    username: mr
    password: FHuma025
  zipkin:
    enabled: false
    locator:
      discovery:
        enabled: true

flywaydb: 
  locations: db/oracle

server: 
  port: 18006
  
mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.feedback.entity
  
api:
  endpoint: /api  
  
priv:
  roles: 
    admin: 
      - mapps.feedback.submit
      - mapps.feedback.isadmin
      - mapps.feedback.delete
      - mapps.feedback.query
      - mapps.feedback.detail
      - mapps.feedback.update
      - mapps.feedback.user
    user: 
      - mapps.feedback.submit
      - mapps.feedback.isadmin

mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: mapps-feedback
    appType: 4
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: https://miap.cc:8209/PageRedirect?path=login.jsp
  mos:
    serviceUrl: http://192.168.160.72:7777/mos/api  
  

services: 
  fileservice:
    serviceUrl: http://192.168.10.210:9081/api
    appKey: meetingroom
    appSecret: FHuma025
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload

client: 
  appId: feedback
  appName: 在线反馈
  
logging:
  path: logs