# with this config, eureka running standalone mode.       
# High Availability, Zones and Regions @See http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_high_availability_zones_and_regions
server:
  port: 8761

api:
  endpoint: /api 

eureka:
  server: 
    enableSelfPreservation: true
  instance:
    hostname: sm.mapps.ip
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
    
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka   
      
security:
  ignored: /api/**, /eureka/**
  basic: 
    enabled: false
  user:
    name: 1
    password: 1     
      
spring: 
  application:
    name: mapps-servicemanager     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.160.87:5432/sm2
    username: mr
    password: 123456 
  profiles:
    active: native
  redis:
    database: 6 # Redis数据库索引（默认为0）
    host: 192.168.160.45
    port: 6379
    password:   # Redis服务器连接密码（默认为空）
    pool:
      max-active: 5 # 连接池最大连接数（使用负值表示没有限制）
      max-waite: 60 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 2 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000 # 连接超时时间（毫秒）

flywaydb: 
  locations: db/migration        
  
mybatis:  
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.servicemanager.entity  

priv:
  roles: 
    admin: 
      - mapps.servicemanager.database.list
      - mapps.servicemanager.database.detail
      - mapps.servicemanager.database.add
      - mapps.servicemanager.database.save
      - mapps.servicemanager.database.create
      - mapps.servicemanager.database.stop
      - mapps.servicemanager.database.start
      - mapps.servicemanager.database.testByList
      - mapps.servicemanager.database.test
      - mapps.servicemanager.redis.list
      - mapps.servicemanager.redis.detail
      - mapps.servicemanager.redis.add
      - mapps.servicemanager.redis.edit
      - mapps.servicemanager.redis.disable
      - mapps.servicemanager.redis.enable
      - mapps.servicemanager.redis.testByList
      - mapps.servicemanager.redis.test
      - mapps.servicemanager.route.query
      - mapps.servicemanager.route.detail
      - mapps.servicemanager.route.edit
      - mapps.servicemanager.route.addReg
      - mapps.servicemanager.route.testReg
      - mapps.servicemanager.route.saveReg
      - mapps.servicemanager.route.addEx
      - mapps.servicemanager.route.saveEx
      - mapps.servicemanager.route.disable
      - mapps.servicemanager.route.enable
      - mapps.servicemanager.route.queryservice
      - mapps.servicemanager.server.restart
      - mapps.servicemanager.resource.setup
      - mapps.servicemanager.resource.get
      - mapps.servicemanager.svcauth.assign
      - mapps.servicemanager.svcauth.createappkey
      - mapps.servicemanager.svcauth.get
      - mapps.servicemanager.svcauth.delete
      - mapps.servicemanager.app.status
      - mapps.servicemanager.app.list
      - mapps.servicemanager.app.config.save
      - mapps.servicemanager.app.config.load
      - mapps.servicemanager.dependecies.get
      - mapps.servicemanager.app.saveform
      - mapps.servicemanager.service.restartstatus
      - mapps.servicemanager.resourcelist.get
      - mapps.servicemanager.dependecies.offget
      - mapps.servicemanager.resource.info.list
      - mapps.servicemanager.resource.info.detail
      - mapps.servicemanager.resource.info.add
      - mapps.servicemanager.resource.info.edit
      - mapps.servicemanager.resource.disable
      - mapps.servicemanager.resource.enable
      - mapps.servicemanager.resource.type.list
      - mapps.servicemanager.resource.type.item
      - mapps.servicemanager.measurement.query
      - mapps.servicemanager.measurement.list
      - mapps.servicemanager.measurement.detail
      - mapps.servicemanager.measurement.add
      - mapps.servicemanager.measurement.edit
      - mapps.servicemanager.field.list
      - mapps.servicemanager.field.value
      - mapps.servicemanager.field.add
      - mapps.servicemanager.field.edit
      - mapps.servicemanager.field.delete
      - mapps.servicemanager.unit.get
      - mapps.servicemanager.tag.query
      - mapps.servicemanager.tag.save
      - mapps.servicemanager.sample.query
      - mapps.servicemanager.sample.disable
      - mapps.servicemanager.sample.enable
      - mapps.servicemanager.sample.add
      - mapps.servicemanager.sample.edit
      - mapps.servicemanager.sample.detail
      - mapps.servicemanager.retention.query
      - mapps.servicemanager.retention.add
      - mapps.servicemanager.retention.edit
      - mapps.servicemanager.retention.delete
      - mapps.servicemanager.retention.disable
      - mapps.servicemanager.retention.enable
      - mapps.servicemanager.retention.getfrominflux
      - mapps.servicemanager.retention.detail
      - mapps.servicemanager.rule.query
      - mapps.servicemanager.rule.disable
      - mapps.servicemanager.rule.enable
      - mapps.servicemanager.rule.save
      - mapps.servicemanager.rule.detail
      - mapps.servicemanager.filter.get
    user: 
      - mapps.servicemanager.app.list 


mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    mngFilter: true
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: https://192.168.160.98:8443/m
  mos:
    serviceUrl: http://192.168.160.72:7777/mos/api  
    
gateway: 
  serviceUrl: http://nginx.ip:7001/gw                   # 需配置为nginx的反向代理服务的地址，且建议使用内网地址                     
  security:
    key: MY_kEY_x12   
    
logging:
  path: logs
   
influxdb: 
  serviceUrl: http://influxdb.ip:8086                   # influxdb的地址，不要使用localhost和127.0.0.1
  adminUser: admin                                      # influxdb默认的管理员用户名密码，可以通过influx管理控制台修改
  adminPass: FHuma025
  
kapacitor: 
  serviceUrl: http://kapacitor.ip:9092/kapacitor/v1     # kapactior的地址，不要使用localhost和127.0.0.1
  osName: linux                                         # 选填 windows linux

sms:  
  key: A@Xbc123_W                                       # 该key为用于端口服务发送的key，一般情况下请在安装时修改，安装后修改可能会影响预警短信的发送，如果修改需重新保存预警规则
