servicemanager:
  endpoint: http://sm.mapps.ip:8761

eureka:
  client:
    enabled: true
    region: mapps
    serviceUrl:
      defaultZone: ${servicemanager.endpoint}/eureka
    healthcheck:
      enabled: true    
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}  
    metadataMap:
      appName: 活动报名                            # 应用名称
      logo: /logo.png                          # 应用logo 
      remarks: 描述                             # 应用描述
      mgr-port: ${management.port}                  # 管理端口
      mgr-context-path: ${management.context-path}  # 管理endpoint的context path
      configProperties:                         # 配置属性
        - key: mplus.sso.serviceUrl
          name: mplus第三方接入地址
          type: text
          remark: mplus可供访问的第三方接入地址，一般为内网地址，支持https
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: http://192.168.160.98:6001/thirdpartaccess
        - key: mplus.sso.appKey
          name: 第三方接入key
          type: text
          remark: mplus第三方接入的appKey
          size: 50
          options: null
          regex: \w+
          group: 通用设置
          default: mr
        - key: mplus.sso.secret
          name: 第三方接入密钥
          type: text
          remark: mplus第三方接入的密钥
          size: 50
          options: null
          regex: \w+
          group: 通用设置
          default: FHuma025
        - key: mplus.login.serviceUrl
          name: mplus登录接口地址
          type: text
          remark: mplus可供访问的客户端登录地址，一般为内网地址，支持https
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: http://192.168.160.98:6001/clientaccess
        - key: mplus.login.loginPage
          name: 自服务门户登录页面
          type: text
          remark: mplus自服务门户的登录页面地址
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: https://miap.cc:8209/PageRedirect?path=login.jsp
        - key: mplus.mos.serviceUrl
          name: mos接口地址
          type: text
          remark: mos接口地址
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: http://192.168.160.154:7777/mos/api  
        - key: mail.host
          name: 发件服务器地址
          type: text
          remark: 发件服务器的域名或ip(不含http://或https://头)
          size: 255
          options: null
          regex: \S+
          group: 通用设置
          default: null
        - key: mail.account
          name: 发件邮箱账号
          type: text
          remark: 报名表发送邮箱的账号
          size: 255
          options: null
          regex: ^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$
          group: 通用设置
          default: null
        - key: mail.password
          name: 发件邮箱密码
          type: text
          remark: 报名表发送邮箱的密码
          size: 255
          options: null
          regex: 
          group: 通用设置
          default: null
        - key: workcircle.id
          name: 工作圈接入id
          type: text
          remark: 工作圈的accessid
          size: 255
          options: null
          regex: 
          group: 通用设置
          default: 250446ef-9e17-4fa3-bd5e-b80419d77183
        - key: activity.im-on-off
          name: im开关
          type: radio
          remark: 是否启用im聊天
          size: 255
          options: true:开,false:关
          regex: "(true)|(false)"
          group: 通用设置
          default: true
      dependencies:
        services: mapps-fileservice
        resources:
          database: default
          redis: default
      
jdbc-url:
  oracle: jdbc:oracle:thin:@${resources.database.default.host:}:${resources.database.default.port:1521}:${resources.database.default.db:}
  postgresql: jdbc:postgresql://${resources.database.default.host:}:${resources.database.default.port:5432}/${resources.database.default.db:}
  mysql: jdbc:mysql://${resources.database.default.host:}:${resources.database.default.port:3306}/${resources.database.default.db:}?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

spring:  
  application:
    name: mapps-activity     
  jmx:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${jdbc-url.${resources.database.default.type:postgresql}}
    username: ${resources.database.default.username}
    password: ${resources.database.default.password}
  redis:
    database: ${resources.redis.default.dbIndex:0} # Redis数据库索引（默认为0）
    host: ${resources.redis.default.host:default.redis.ip}
    port: ${resources.redis.default.port:6379}
    password: ${resources.redis.default.password:}   # Redis服务器连接密码（默认为空）
    pool:
      max-active: 1 # 连接池最大连接数（使用负值表示没有限制）
      max-waite: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）
    
server: 
  port: 18012    
  
management:
  context-path: /__mng__
  port: 38012

endpoints:
  restart:
    enabled: true

sqllocaltion:
  oracle: db/oracle
  postgresql: db/migration
  mysql: db/mysql
    
flywaydb:
  locations: ${sqllocaltion.${resources.database.default.type:postgresql}} 
  
mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.activity.entity
  
api:
  endpoint: /api  
  
priv:
  roles: 
    admin: 
      - mapps.fileservice.file.upload
      - mapps.activity.one.add
      - mapps.activity.one.delete
      - mapps.activity.list.query
      - mapps.activity.list.queryMyEnter
      - mapps.activity.one.enter
      - mapps.activity.list.queryEnter
      - mapps.activity.list.queryMyCreate
      - mapps.activity.privilege.add
      - mapps.activity.privilege.query
      - mapps.activity.group.join
      - mapps.thirdpart.mobileark.createImGroup
      - mapps.thirdpart.mobileark.joingroup
      - mapps.thirdpart.mobileark.getpersondocs
      - mapps.thirdpart.mobileark.getdocurl
      - mapps.thirdpart.mobileark.getdepartments
      - mapps.thirdpart.mobileark.getusers
      - mapps.thirdpart.mobileark.getlimtedusers
      - mapps.activity.exportEnter
      - mapps.activity.circle.share
    user: 
      - mapps.fileservice.file.upload
      - mapps.activity.one.add
      - mapps.activity.one.delete
      - mapps.activity.list.query
      - mapps.activity.list.queryMyEnter
      - mapps.activity.list.queryMyCreate
      - mapps.activity.one.enter
      - mapps.activity.list.queryEnter
      - mapps.activity.privilege.add
      - mapps.activity.privilege.query
      - mapps.activity.group.join
      - mapps.thirdpart.mobileark.createImGroup
      - mapps.thirdpart.mobileark.joingroup
      - mapps.thirdpart.mobileark.getpersondocs
      - mapps.thirdpart.mobileark.getdocurl
      - mapps.thirdpart.mobileark.getdepartments
      - mapps.thirdpart.mobileark.getusers
      - mapps.activity.exportEnter
      - mapps.activity.circle.share


mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: mapps-activity
    appType: 4
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: https://miap.cc:8209/PageRedirect?path=login.jsp
  mos:
    serviceUrl: http://192.168.160.154:7777/mos/api  
    
services: 
  fileservice:
    serviceUrl: ${services.mapps-fileservice.serviceUrl:}/api
    appKey: ${services.mapps-fileservice.appkey:}
    appSecret: ${services.mapps-fileservice.secret:}
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload
  
client: 
  appId: activity
  appName: 活动报名

mail: 
  host: 192.168.100.4
  account: liyanwei@nj.fiberhome.com.cn
  password: r4408866
  
logging:
  path: logs 
  
workcircle: 
  id: 250446ef-9e17-4fa3-bd5e-b80419d77183
  
activity:
  im-on-off: false # im开关