eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
      
spring: 
  application:
    name: mapps-activity     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.160.87:5432/mapps
    username: mapps
    password: FHuma025 
  redis:
    database: 5 # Redis数据库索引（默认为0）
    host: 192.168.160.45
    port: 6379
    password:   # Redis服务器连接密码（默认为空）
    pool:
      max-active: 1 # 连接池最大连接数（使用负值表示没有限制）
      max-waite: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）
  zipkin:
    enabled: false
    locator:
      discovery:
        enabled: true
    
flywaydb: 
  locations: db/migration    
  
server: 
  port: 18012
    
mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.activity.entity
   
api:
  endpoint: /api  

priv:
  roles: 
    admin: 
      - mapps.fileservice.file.upload
      - mapps.activity.one.add
      - mapps.activity.one.delete
      - mapps.activity.list.query
      - mapps.activity.list.queryMyEnter
      - mapps.activity.one.enter
      - mapps.activity.list.queryEnter
      - mapps.activity.list.queryMyCreate
      - mapps.activity.privilege.add
      - mapps.activity.privilege.query
      - mapps.activity.group.join
      - mapps.thirdpart.mobileark.createImGroup
      - mapps.thirdpart.mobileark.joingroup
      - mapps.thirdpart.mobileark.getpersondocs
      - mapps.thirdpart.mobileark.getdocurl
      - mapps.thirdpart.mobileark.getdepartments
      - mapps.thirdpart.mobileark.getusers
      - mapps.thirdpart.mobileark.getlimtedusers
      - mapps.activity.exportEnter
      - mapps.activity.circle.share
    user: 
      - mapps.fileservice.file.upload
      - mapps.activity.one.add
      - mapps.activity.one.delete
      - mapps.activity.list.query
      - mapps.activity.list.queryMyEnter
      - mapps.activity.list.queryMyCreate
      - mapps.activity.one.enter
      - mapps.activity.list.queryEnter
      - mapps.activity.privilege.add
      - mapps.activity.privilege.query
      - mapps.activity.group.join
      - mapps.thirdpart.mobileark.createImGroup
      - mapps.thirdpart.mobileark.joingroup
      - mapps.thirdpart.mobileark.getpersondocs
      - mapps.thirdpart.mobileark.getdocurl
      - mapps.thirdpart.mobileark.getdepartments
      - mapps.thirdpart.mobileark.getusers
      - mapps.activity.exportEnter
      - mapps.activity.circle.share
mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: 
    appType: 4
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: https://miap.cc:8209/PageRedirect?path=login.jsp
  imsg:
    serviceUrl: http://192.168.160.72:7777/mos/api
  contacts:
    serviceUrl: http://192.168.160.72:7777/mos/api

services: 
  fileservice:
    serviceUrl: http://192.168.10.210:9081/api
    appKey: meetingroom
    appSecret: FHuma025
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload

web:
  url: http://miap.cc:9100/mt

client: 
  appId: activity
  appName: 活动报名

mail: 
  host: 192.168.100.4  #smtp服务器ip
  account: xxx@nj.fiberhome.com.cn
  password: password
  
logging:
  path: logs 
  
workcircle: 
  id: 250446ef-9e17-4fa3-bd5e-b80419d77183
  
activity:
  im-on-off: false # im开关