spring:
  application:
    name: mapps-trip     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@192.168.160.45:1521:orcl
    username: mr
    password: FHuma025 
      
flywaydb: 
  locations: db/oracle