servicemanager:
  endpoint: http://sm.mapps.ip:8761

eureka:
  client:
    enabled: true
    region: mapps
    serviceUrl:
      defaultZone: ${servicemanager.endpoint}/eureka
    healthcheck:
      enabled: true    
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}  
    metadataMap:
      appName: 签到                            # 应用名称
      logo: /logo.png                          # 应用logo 
      remarks: 描述                             # 应用描述
      mgr-port: ${management.port}                  # 管理端口
      mgr-context-path: ${management.context-path}  # 管理endpoint的context path
      configProperties:                         # 配置属性
        - key: mplus.sso.serviceUrl
          name: mplus第三方接入地址
          type: text
          remark: mplus可供访问的第三方接入地址，一般为内网地址，支持https
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: http://192.168.160.98:6001/thirdpartaccess
        - key: mplus.sso.appKey
          name: 第三方接入key
          type: text
          remark: mplus第三方接入的appKey
          size: 50
          options: null
          regex: \w+
          group: 通用设置
          default: mr
        - key: mplus.sso.secret
          name: 第三方接入密钥
          type: text
          remark: mplus第三方接入的密钥
          size: 50
          options: null
          regex: \w+
          group: 通用设置
          default: FHuma025
        - key: mplus.login.serviceUrl
          name: mplus登录接口地址
          type: text
          remark: mplus可供访问的客户端登录地址，一般为内网地址，支持https
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: http://192.168.160.98:6001/clientaccess
        - key: mplus.login.loginPage
          name: 自服务门户登录页面
          type: text
          remark: mplus自服务门户的登录页面地址
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: https://miap.cc:8209/PageRedirect?path=login.jsp
        - key: mplus.mos.serviceUrl
          name: mos接口地址
          type: text
          remark: mos接口地址
          size: 255
          options: null
          regex: http(s)?://([\w-]+\.)+[\w-]+(:[0-9]+)?(/[\w- ./?%&=]*)?
          group: 通用设置
          default: http://192.168.160.154:7777/mos/api  
      dependencies:
        services: mapps-fileservice
        resources:
          database: default
      
jdbc-url:
  oracle: jdbc:oracle:thin:@${resources.database.default.host:}:${resources.database.default.port:1521}:${resources.database.default.db:}
  postgresql: jdbc:postgresql://${resources.database.default.host:}:${resources.database.default.port:5432}/${resources.database.default.db:}
  mysql: jdbc:mysql://${resources.database.default.host:}:${resources.database.default.port:3306}/${resources.database.default.db:}?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

spring:  
  application:
    name: mapps-sign    
  jmx:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${jdbc-url.${resources.database.default.type:postgresql}}
    username: ${resources.database.default.username}
    password: ${resources.database.default.password}
    
server: 
  port: 18005    
  
management:
  context-path: /__mng__
  port: 38005

endpoints:
  restart:
    enabled: true

sqllocaltion:
  oracle: db/oracle
  postgresql: db/migration
  mysql: db/mysql
    
flywaydb:
  locations: ${sqllocaltion.${resources.database.default.type:postgresql}} 
  
mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.sign.entity
  
api:
  endpoint: /api  
  
priv:
  roles: 
    admin: 
      - mapps.sign.query
      - mapps.sign.add
      - mapps.sign.servertime
      - mapps.sign.detail
      - mapps.sign.queryadmin
      - mapps.sign.queryStat
      - mapps.sign.lastSign.query
      - mapps.thirdpart.mobileark.getusers
      - mapps.sign.getUserIcon
    user: 
      - mapps.sign.query
      - mapps.sign.add
      - mapps.sign.servertime
      - mapps.sign.detail
      - mapps.sign.queryadmin
      - mapps.sign.queryStat
      - mapps.sign.lastSign.query
      - mapps.thirdpart.mobileark.getusers
      - mapps.sign.getUserIcon


mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: mapps-sign
    appType: 4
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: https://miap.cc:8209/PageRedirect?path=login.jsp
  mos:
    serviceUrl: http://192.168.160.154:7777/mos/api  
    
services: 
  fileservice:
    serviceUrl: ${services.mapps-fileservice.serviceUrl:}/api
    appKey: ${services.mapps-fileservice.appkey:}
    appSecret: ${services.mapps-fileservice.secret:}
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload
  
client: 
  appId: sign
  appName: 签到
  
sign:
  upgrade: 
    migrate: false  

logging:
  path: logs