servicemanager:
  endpoint: http://sm.mapps.ip:8761

eureka:
  client:
    enabled: true
    region: mapps
    serviceUrl:
      defaultZone: ${servicemanager.endpoint}/eureka
    healthcheck:
      enabled: true    
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}  
    metadataMap:
      appName: 签到                            # 应用名称
      logo: /logo.png                          # 应用logo 
      remarks: 描述                             # 应用描述
      mgr-port: ${management.port}                  # 管理端口
      mgr-context-path: ${management.context-path}  # 管理endpoint的context path
      configProperties:                         # 配置属性
      dependencies:
        services: mapps-fileservice
        resources:
          database: default
          mplus: default
      
jdbc-url:
  oracle: jdbc:oracle:thin:@${resources.database.default.host:}:${resources.database.default.port:1521}:${resources.database.default.db:}
  postgresql: jdbc:postgresql://${resources.database.default.host:}:${resources.database.default.port:5432}/${resources.database.default.db:}
  mysql: jdbc:mysql://${resources.database.default.host:}:${resources.database.default.port:3306}/${resources.database.default.db:}?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

spring:  
  application:
    name: mapps-sign    
  jmx:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${jdbc-url.${resources.database.default.type:postgresql}}
    username: ${resources.database.default.username}
    password: ${resources.database.default.password}
    
server: 
  port: 18005    
  
management:
  context-path: /__mng__
  port: 38005

endpoints:
  restart:
    enabled: true

sqllocaltion:
  oracle: db/oracle
  postgresql: db/migration
  mysql: db/mysql
    
flywaydb:
  locations: ${sqllocaltion.${resources.database.default.type:postgresql}} 
  
mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.sign.entity
  
api:
  endpoint: /api  
  
priv:
  roles: 
    admin: 
      - mapps.sign.query
      - mapps.sign.add
      - mapps.sign.servertime
      - mapps.sign.detail
      - mapps.sign.queryadmin
      - mapps.sign.queryStat
      - mapps.sign.lastSign.query
      - mapps.thirdpart.mobileark.getusers
      - mapps.sign.getUserIcon
    user: 
      - mapps.sign.query
      - mapps.sign.add
      - mapps.sign.servertime
      - mapps.sign.detail
      - mapps.sign.queryadmin
      - mapps.sign.queryStat
      - mapps.sign.lastSign.query
      - mapps.thirdpart.mobileark.getusers
      - mapps.sign.getUserIcon


mplus: 
  sso:
    serviceUrl: ${resources.mplus.default.mplus.sso.serviceUrl:}
    appKey: ${resources.mplus.default.mplus.sso.appKey:}
    secret: ${resources.mplus.default.mplus.sso.secret:}
    appId: mapps-sign
    appType: 4
  login:
    serviceUrl: ${resources.mplus.default.mplus.login.serviceUrl:}
    loginPage: ${resources.mplus.default.mplus.login.loginPage:}
    
services: 
  fileservice:
    serviceUrl: ${services.mapps-fileservice.serviceUrl:}/api
    appKey: ${services.mapps-fileservice.appkey:}
    appSecret: ${services.mapps-fileservice.secret:}
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload
  
client: 
  appId: sign
  appName: 签到
  
sign:
  upgrade: 
    migrate: false  

logging:
  path: logs