ALTER TABLE SM_APP_METADATA ADD ( "METADATA2" CLOB NULL);

update SM_APP_METADATA set metadata2 = metadata;

ALTER TABLE SM_APP_METADATA DROP ("METADATA");

ALTER TABLE SM_APP_METADATA RENAME COLUMN METADATA2 to METADATA;