servicemanager:
  endpoint: http://sm.mapps.ip:8761

eureka:
  client:
    enabled: true
    region: mapps
    serviceUrl:
      defaultZone: ${servicemanager.endpoint}/eureka
    healthcheck:
      enabled: true    
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}  
    metadataMap:
      appName: 文件服务                         # 应用名称
      logo: /logo.png                          # 应用logo 
      remarks: 描述                             # 应用描述
      portal: /websso                           # 自服务门户集成入口
      mgr-port: ${management.port}                  # 管理端口
      mgr-context-path: ${management.context-path}  # 管理endpoint的context path
      configProperties:                         # 配置属性
        - key: fileservice.store                # 属性key
          name: 存储类型                         #属性名称  
          type: radio                            #类型，text,radio,checkbox           
          remark: 选择文件系统或是fdfs存储        #说明
          size: 100                              #值列长度 
          options: file:文件系统,fdfs:FastDFS     #radio或者checkbox时的选项，可为空
          regex: "(file)|(fdfs)"                  #校验正则表达式
          group: 通用设置                         #通用设置
          default: file                          #缺省值
        - key: fileservice.path  
          name: 存储路径   
          type: text         
          remark: 存储类型为file时的文件存储路径，一般使用共享存储
          size: 100  
          options: 
          regex: 
          group: 通用设置
          default: upload
      dependencies:                             # 依赖声明
        services:                               # 依赖的服务，id，逗号分隔
        resources:                              # 依赖的资源
          database: default                     # resId: resCode(资源id： 资源代码)
      
jdbc-url:
  oracle: jdbc:oracle:thin:@${resources.database.default.host}:${resources.database.default.port}:${resources.database.default.db}
  postgresql: jdbc:postgresql://${resources.database.default.host}:${resources.database.default.port}/${resources.databa

spring:  
  application:
    name: mapps-fileservice    
  jmx:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${jdbc-url.${resources.database.default.type:postgresql}}
    username: ${resources.database.default.username}
    password: ${resources.database.default.password}
    
sqllocaltion:
  oracle: db/oracle
  postgresql: db/migration 

flywaydb: 
  locations: ${sqllocaltion.${resources.database.default.type}}
   
management:
  context-path: /__mng__
  port: 38010  
#  address: 192.168.4.161

endpoints:
  restart:
    enabled: true

api:
  endpoint: /api  

fdfs:
  webRoot: http://miap.cc:9100/img/
  soTimeout: 1501
  connectTimeout: 601
  trackerList:            #TrackerList参数,支持多个
    - 192.168.160.162:22122

server:
  port: 9081
  
logging:
  path: logs