eureka:
  client:
    enabled: false

spring:
  application:
    name: mapps-fileservice    
  jmx:
    enabled: false   
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.160.103:5432/mr_test
    username: mr
    password: 123456

flywaydb: 
  locations: db/migration

fileservice:
  store: file # 可选 file 和 fdfs，即文件存储和fastdfs的分布式存储
  path: upload  # 如果使用的存储方式（fileservice.store）为“file", 需配置为文件存储路径.
 
fdfs:
  webRoot: http://miap.cc:9100/img/
  soTimeout: 1501
  connectTimeout: 601
  trackerList:            #TrackerList参数,支持多个
    - 192.168.160.162:22122
    
server:
  port: 9081
  
logging:
  path: logs    