# redis config
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.160.45
    port: 6379
    password:   # Redis服务器连接密码（默认为空）
    pool:
      max-active: 1 # 连接池最大连接数（使用负值表示没有限制）
      max-waite: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000 # 连接超时时间（毫秒）
    