spring:
  application:
    name: mapps-servicemanager     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@192.168.70.111:1521:orcl
    username: mapps
    password: FHuma025 
      
flywaydb: 
  locations: db/oracle