spring:
  application:
    name: mapps-meetingroom     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@192.168.160.45:1521:orcl
    username: mr
    password: FHuma025 
      
flywaydb: 
  locations: db/oracle
  
mplus: 
  sso:
    serviceUrl: http://192.168.160.103:7001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: meetingroom
    appType: 5
  login:
    serviceUrl: http://192.168.160.103:7001/clientaccess  