eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
      
spring: 
  application:
    name: mapps-ydzf     
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.160.103:5432/mr
    username: mr
    password: 123456 

flywaydb: 
  locations: db/migration
    
mybatis:  
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.fiberhome.mapps.ydzf.entity

server: 
  port: 18013    
 
management:
  context-path: /__mng__
  port: 38013
  address: 127.0.0.1    
  
api:
  endpoint: /api
  key: -CfPhxfqTIOQagwZGCh4sg
  secret: xnRtQYYEub7PKrKWzMiE2DKr9XxoKRCbtHgh
  getaccountreport: https://www.zoomus.cn/v1/report/getaccountreport
  getmeetinginfo: https://www.zoomus.cn/v1/meeting/get
  endmeeting: https://www.zoomus.cn/v1/meeting/end
  goodsdetail: http://gjet.szciqic.net:8001/process/service/mlaw/goodsdetail.do
  containerdetail: http://gjet.szciqic.net:8001/process/service/mlaw/containerdetail.do
    
  
priv:
  roles: 
    admin: 
      - mapps.fileservice.file.upload 
      - mapps.fileservice.file.download 
      - mapps.ydzf.query.list
      - mapps.ydzf.query.detail
      - mapps.ydzf.query.goodsdetail
    user:  
      - mapps.fileservice.file.upload 
      - mapps.fileservice.file.download 
      - mapps.ydzf.query.list
      - mapps.ydzf.query.detail
      - mapps.ydzf.query.goodsdetail

mplus: 
  sso:
    serviceUrl: http://192.168.160.98:6001/thirdpartaccess
    appKey: mr
    secret: FHuma025
    appId: ydzf
    appType: 4
  login:
    serviceUrl: http://192.168.160.98:6001/clientaccess
    loginPage: http://192.168.160.98:6001/p
  

services: 
  fileservice:
    serviceUrl: http://192.168.160.162:9081/api
    appKey: meetingroom
    appSecret: FHuma025
    format: json
    v: 1.0
    method: mapps.fileservice.file.upload
    webRoot: http://192.168.160.162/
    root: D:/IMG/
    imagePath: http://127.0.0.1:18013/api?format=bin&v=1.0&appKey=&method=mapps.fileservice.file.download&directory=
    
meetingroom:
  privilage:
    whiteList: true
    
client: 
  appId: ydzf
  appName: 移动执法

logging:
  path: logs
  
