ALTER TABLE MR_PRIVILEGE MODIFY ( ENTITY_NAME VARCHAR2(255 CHAR));

ALTER TABLE MR_RESERVED MODIFY ( RESERVED_USER_NAME VARCHAR2(255 CHAR));
ALTER TABLE MR_RESERVED MODIFY ( RESERVED_USER_DEPT VARCHAR2(255 CHAR));
ALTER TABLE MR_RESERVED MODIFY ( MEETING_NAME VARCHAR2(255 CHAR));
ALTER TABLE MR_RESERVED MODIFY ( REMARKS VARCHAR2(512 CHAR));

ALTER TABLE MR_ROOM MODIFY ( NAME VARCHAR2(255 CHAR));
ALTER TABLE MR_ROOM MODIFY ( ADDRESS VARCHAR2(255 CHAR));
ALTER TABLE MR_ROOM MODIFY ( REMARKS VARCHAR2(512 CHAR));
ALTER TABLE MR_ROOM MODIFY ( LAYOUT VARCHAR2(255 CHAR));

ALTER TABLE OP_LOG MODIFY ( CONTENT VARCHAR2(4000 CHAR));
ALTER TABLE OP_LOG MODIFY ( USER_NAME VARCHAR2(255 CHAR));
ALTER TABLE OP_LOG MODIFY ( DEPT_NAME VARCHAR2(255 CHAR));