ALTER TABLE DBR_BORROW_RETURN_LOG MODIFY ( DEPT_NAME VARCHAR2(255 CHAR));
ALTER TABLE DBR_BORROW_RETURN_LOG MODIFY ( USER_NAME VARCHAR2(255 CHAR));

ALTER TABLE DBR_DEVICE MODIFY ( USER_NAME VARCHAR2(255 CHAR));
ALTER TABLE DBR_DEVICE MODIFY ( DEVICE_NAME VARCHAR2(255 CHAR));

